// Each project's assets live in public/projects/{id}/
// Expected files: image.{png|jpg|webp} and audio.{wav|mp3|webm}
const projects = [
  {
    id: 1,
    title: "Project 01",
    student: "Student Name",
    description: "A spatial proposal exploring the tension between the historic fabric of the Polish Inn and a new programmatic layer. The project negotiates thresholds between public and intimate, generating a sequence of compressed and released volumes.",
    image: "/projects/1/image.png",
    audio: "/projects/1/audio.wav",
  },
  {
    id: 2,
    title: "Project 02",
    student: "Student Name",
    description: "Rooted in the concept of cultural stratification, this proposal layers time through material and spatial contrast. The courtyard becomes a stage — a mediating element between the city and the interior life of the building.",
    image: "/projects/2/image.png",
    audio: "/projects/2/audio.wav",
  },
  {
    id: 3,
    title: "Project 03",
    student: "Student Name",
    description: "A fragmented composition that breaks the existing envelope into a series of pavilion-like volumes. The spaces between become as important as the spaces within, creating a porous cultural infrastructure.",
    image: "/projects/3/image.png",
    audio: "/projects/3/audio.wav",
  },
  {
    id: 4,
    title: "Project 04",
    student: "Student Name",
    description: "This project treats the site as a topographic field — a landscape of platforms and levels that guide movement through the cultural program. Monumentality is avoided in favor of horizontal continuity.",
    image: "/projects/4/image.png",
    audio: "/projects/4/audio.wav",
  },
  {
    id: 5,
    title: "Project 05",
    student: "Student Name",
    description: "A proposal centered on light and shadow as architectural tools. Narrow apertures and deep voids choreograph the visitor's experience across the day, making the building a living instrument of perception.",
    image: "/projects/5/image.png",
    audio: "/projects/5/audio.wav",
  },
  {
    id: 6,
    title: "Project 06",
    student: "Student Name",
    description: "The project interrogates the boundary between inside and outside, proposing a continuous loop of space that begins on the street and spirals through the cultural program without a clear beginning or end.",
    image: "/projects/6/image.png",
    audio: "/projects/6/audio.wav",
  },
  {
    id: 7,
    title: "Project 07",
    student: "Student Name",
    description: "Inspired by the acoustic properties of traditional Romanian vernacular spaces, this project embeds sound into its spatial logic. Rooms are tuned — their dimensions and materials chosen for resonance and stillness.",
    image: "/projects/7/image.png",
    audio: "/projects/7/audio.wav",
  },
  {
    id: 8,
    title: "Project 08",
    student: "Student Name",
    description: "A dense, layered intervention that reads the existing building as a found object. New additions are inserted as precise incisions — minimal, deliberate, creating a dialogue between old and new without erasure.",
    image: "/projects/8/image.png",
    audio: "/projects/8/audio.wav",
  },
  {
    id: 9,
    title: "Project 09",
    student: "Student Name",
    description: "The proposal transforms the courtyard into the heart of the cultural center — a communal void around which all activities orbit. The architecture recedes, privileging gathering over spectacle.",
    image: "/projects/9/image.png",
    audio: "/projects/9/audio.wav",
  },
  {
    id: 10,
    title: "Project 10",
    student: "Student Name",
    description: "A project driven by movement and flow — ramps, bridges, and elevated walkways connect disparate programs into a single continuous promenade. The journey through the building becomes as meaningful as the destinations.",
    image: "/projects/10/image.png",
    audio: "/projects/10/audio.wav",
  },
  {
    id: 11,
    title: "Project 11",
    student: "Student Name",
    description: "Drawing from the idea of cultural memory as sediment, this proposal builds upward in geological layers — each floor a different epoch, material palette, and spatial character, unified by a shared vertical core.",
    image: "/projects/11/image.png",
    audio: "/projects/11/audio.wav",
  },
  {
    id: 12,
    title: "Project 12",
    student: "Student Name",
    description: "The final proposal in the series reduces the cultural center to its most essential act — shelter and gathering. A single large roof unifies fragmented programs beneath it, creating a democratic space of possibility.",
    image: "/projects/12/image.png",
    audio: "/projects/12/audio.wav",
  },
  {
    id: 13,
    title: "Project 13",
    student: "Student Name",
    description: "The final proposal in the series reduces the cultural center to its most essential act — shelter and gathering. A single large roof unifies fragmented programs beneath it, creating a democratic space of possibility.",
    image: "/projects/13/image.png",
    audio: "/projects/13/audio.wav",
  },
];

export default projects;